package com.reqws.goland.manifest

/** Stable, non-localized identifiers used by tests, diagnostics, and the UI. */
enum class ManifestErrorCode {
  MANIFEST_NOT_FOUND,
  MANIFEST_NOT_REGULAR_FILE,
  MANIFEST_TOO_LARGE,
  MANIFEST_INVALID_ENCODING,
  MANIFEST_INVALID_JSON,
  MANIFEST_SCHEMA_INVALID,
  UNSUPPORTED_MANIFEST_VERSION,
  WORKSPACE_ROOT_MISMATCH,
  REPOSITORY_DUPLICATE,
  REPOSITORY_PATH_INVALID,
  REPOSITORY_PATH_ESCAPE,
  REPOSITORY_MISSING,
}

/**
 * A manifest failure whose message is deliberately safe to log.
 *
 * Raw JSON, repository URLs, and field values are never included. [field]
 * contains only a schema location generated by this plugin.
 */
class ManifestException internal constructor(
  val code: ManifestErrorCode,
  val field: String? = null,
  val digestSha256: String? = null,
) : Exception(messageFor(code)) {
  internal fun withDigest(digest: String): ManifestException =
    ManifestException(code = code, field = field, digestSha256 = digest)

  companion object {
    private fun messageFor(code: ManifestErrorCode): String = when (code) {
      ManifestErrorCode.MANIFEST_NOT_FOUND -> "ReqWS manifest was not found."
      ManifestErrorCode.MANIFEST_NOT_REGULAR_FILE -> "ReqWS manifest is not a regular file."
      ManifestErrorCode.MANIFEST_TOO_LARGE -> "ReqWS manifest exceeds the size limit."
      ManifestErrorCode.MANIFEST_INVALID_ENCODING -> "ReqWS manifest is not valid UTF-8."
      ManifestErrorCode.MANIFEST_INVALID_JSON -> "ReqWS manifest is not valid JSON."
      ManifestErrorCode.MANIFEST_SCHEMA_INVALID -> "ReqWS manifest does not match schema v1."
      ManifestErrorCode.UNSUPPORTED_MANIFEST_VERSION -> "ReqWS manifest version is unsupported."
      ManifestErrorCode.WORKSPACE_ROOT_MISMATCH -> "ReqWS manifest belongs to another project root."
      ManifestErrorCode.REPOSITORY_DUPLICATE -> "ReqWS manifest contains a duplicate repository."
      ManifestErrorCode.REPOSITORY_PATH_INVALID -> "ReqWS manifest contains an invalid repository path."
      ManifestErrorCode.REPOSITORY_PATH_ESCAPE -> "ReqWS repository path escapes the project root."
      ManifestErrorCode.REPOSITORY_MISSING -> "ReqWS repository directory is missing."
    }
  }
}

enum class ManifestDiagnosticSeverity {
  WARNING,
}

/** No untrusted field value is retained in diagnostics. */
data class ManifestDiagnostic(
  val code: ManifestErrorCode,
  val severity: ManifestDiagnosticSeverity,
  val repositoryIndex: Int? = null,
)
